$\small\textbf{ 1.2.1 Пример}$ $\small\textit{Создать массив 5x2. Создать массив 5x2. Вывести все значения массива,
значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.}$ 

In [1]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


$\small\textbf{1.2.2 Пример}$ $\small\textit{Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.}$ 

In [2]:
import numpy as np
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
d=np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


$\small\textbf{1.2.3 Пример}$ $\small\textit{Создать массив 10x10 со случайными значениями, найти минимум,
максимум и среднее значение.}$ 

In [3]:
import numpy as np
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(),Z.mean()
print(Zmin, Zmax, Zmean)

0.00857856444724947 0.9992711988887232 0.5292411769203738


$\small\textbf{1.2.4 Пример}$ $\small\textit{Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами.}$ 

In [4]:
import numpy as np
A=np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


$\small\textbf{1.2.5 Пример}$ $\small\textit{Выяснить результат следующих выражений:
0 * np.nan , 
np.nan == np.nan ,
np.inf > np.nan ,
np.nan - np.nan ,
0.3 == 3 * 0.1}$ 

In [5]:
import numpy as np
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


$\small\textbf{1.2.6 Пример}$ $\small\textit{Отсортировать массив.}$ 

In [6]:
import numpy as np
arr=np.array([2,1,5,3,7,4,6,8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


$\small\textbf{1.3.1 Задание}$ $\small\textit{Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.}$ 

In [7]:
import numpy as np

matrix = np.zeros((8, 8), dtype=int) 
matrix[::2, ::2] = 1  
matrix[1::2, 1::2] = 1  

print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


$\small\textbf{1.3.2 Задание}$ $\small\textit{Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange}$ 

In [8]:
import numpy as np

matrix = np.zeros((5,5))
matrix += np.arange(5)

print(matrix)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


$\small\textbf{1.3.3 Задание}$ $\textit{Создать массив 3x3x3 со случайными значениями.}$ 

In [9]:
import numpy as np

array = np.random.rand(3, 3, 3)

print(array)


[[[0.41753102 0.00889829 0.97949823]
  [0.82500564 0.86093466 0.1641877 ]
  [0.62619979 0.87183796 0.72002036]]

 [[0.98661415 0.15000667 0.23857899]
  [0.8661748  0.90308904 0.50351258]
  [0.05460981 0.87966331 0.11936056]]

 [[0.450067   0.20244263 0.14953257]
  [0.287735   0.92146206 0.97702478]
  [0.85846641 0.29174472 0.16098527]]]


$\small\textbf{1.3.4 Задание}$ $\small\textit{Создать матрицу с 0 внутри, и 1 на границах.}$ 

In [10]:
import numpy as np

n_rows = 5
n_cols = 5

matrix = np.zeros((n_rows, n_cols))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print(matrix)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


$\small\textbf{1.3.5 Задание}$ $\small\textit{Создайте массив и отсортируйте его по убыванию.}$ 

In [11]:
import numpy as np

arr = np.array([5, 2, 8, 1, 9, 3])
sorted_arr = np.sort(arr)[::-1]

print(sorted_arr)


[9 8 5 3 2 1]


$\small\textbf{1.3.6 Задание}$ $\small\textit{Создайте матрицу, выведите ее форму, размер и размерность.}$ 

In [12]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)
print("Форма:", matrix.shape)
print("Размер:", matrix.size)
print("Размерность:", matrix.ndim)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма: (3, 3)
Размер: 9
Размерность: 2


$\small\textbf{2.2.1 Пример}$ $\small\textit{Создать Series из списка Python, словаря Python, и массива Numpy(установить буквенные метки для последнего.}$ 

In [13]:
import pandas as pd
import numpy as np
lst=[1,2,3,4,5]
d={'a':1,'b':2,'c':3}
ndarr=np.array([1,2,3,4,5])

s1=pd.Series(lst)
s2=pd.Series(d)
s3=pd.Series(ndarr,['a','b','c','d','e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


$\small\textbf{2.2.2 Пример}$ $\small\textit{Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме)}$ 

In [14]:
import pandas as pd
s1=pd.Series([1,2,3,4,5],['a','b','c','d','e'])
s2=pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


$\small\textbf{2.2.3 Пример}$ $\small\textit{Создайте новый фрейм данных.}$ 

In [15]:
import pandas as pd
dataframe=pd.DataFrame()
dataframe['Имя']=['Джеки Джексон','Стивен Стивенсон']
dataframe['Возраст']=[38,25]
dataframe['Водитель']=[True,False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

$\small\textbf{2.2.4 Пример}$ $\small\textit{Загрузите фрейм данных по ссылке:
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titan
ic.csv}$ 

In [16]:
import pandas as pd
url='https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe=pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

$\small\textbf{2.2.5 Пример}$ $\small\textit{Проанализировать характеристики фрейма данных.}$ 

In [17]:
import pandas as pd
url='https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe=pd.read_csv(url)
print(dataframe.head(2))
print("\n")
print(dataframe.tail(3))
print("\n")
print(dataframe.shape)
print("\n")
print(dataframe.describe())

                           Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1


                  Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0


(1313, 6)


              Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000


$\small\textbf{2.2.6 Пример}$ $\small\textit{Выберите индивидуальные данные или срезы фрейма данных}$ 

In [18]:
import pandas as pd
url='https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe=pd.read_csv(url)
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

$\small\textbf{2.2.7 Пример}$ $\small\textit{Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.}$ 

In [19]:
import pandas as pd
url='https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe=pd.read_csv(url)
dataframe[dataframe['PClass']=='1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

$\small\textbf{2.3.1 Задание}$ $\small\textit{Найдите евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.}$

In [20]:
import pandas as pd

a = pd.Series([2, 6, 3, 8])
b = pd.Series([1, 9, 4, 7])

print(sum((a - b)**2)**0.5)

3.4641016151377544


$\small\textbf{2.3.2 Задание}$ $\small\textit{Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).}$ 

In [21]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/wine.csv'
dataframe = pd.read_csv(url)
print(dataframe.head())


       1     2     3     4    5     6     7     8     9    10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  y  
0  1065  1  
1  1050  1  
2  1185  1  
3  1480  1  
4   735  1  


$\small\textbf{2.3.3 Задание}$ $\small\textit{Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.}$ 

In [22]:
import pandas as pd

url = 'https://raw.githubusercontent.com/akmand/datasets/main/wine.csv'
dataframe = pd.read_csv(url)

print(dataframe.columns)
# Анализ характеристик фрейма
print(dataframe.head(2))
print("\n")
print(dataframe.tail(3))
print("\n")
print(dataframe.shape)
print("\n")
print(dataframe.describe())  # Печать сводной статистики
print("\n")

# Выбор отдельных данных или фрагментов 
print(dataframe['1'])  # Выбор одного столбца
print("\n")
print(dataframe.iloc[2:5, 3:6])  # Выбор фрагмента столбцов и строк iloc
print("\n")

# Фильтр фрейма данных на основе условия
filtered_df = dataframe[dataframe['1'] > 13.0]  # Выбор строк, где 1 столбец > 13.0
print(filtered_df.head())



Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13',
       'y'],
      dtype='object')
       1     2     3     4    5     6     7     8     9    10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   

     13  y  
0  1065  1  
1  1050  1  


         1     2     3     4    5     6     7     8     9    10    11    12  \
175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.2  0.59  1.56   
176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.3  0.60  1.62   
177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.2  0.61  1.60   

      13  y  
175  835  3  
176  840  3  
177  560  3  


(178, 14)


                1           2           3           4           5           6  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean    13.000618    2.336348    2.366517   19.494944   99.741573  

$\small\textbf{3.2.1 Пример}$ $\small\textit{Прошкалируйте числовой признак в диапазон между двумя значениями}$ 

In [23]:
import numpy as np
from sklearn import preprocessing
feature=np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])
minmax_scale=preprocessing.MinMaxScaler(feature_range=(0,1))
scaled_feature=minmax_scale.fit_transform(feature)
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

$\small\textbf{3.2.2 Пример}$ $\small\textit{Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1}$ 

In [24]:
import numpy as np
from sklearn import preprocessing
x=np.array([[-1000.1],[-200.2],[500.5],[600.6],[9000.9]])
scaler=preprocessing.StandardScaler()
standardized=scaler.fit_transform(x)
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:",standardized.std())
standardized

Среднее: 0
Стандартное отклонение: 1.0


array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

$\small\textbf{3.2.3. Пример}$ $\textit{Дан фрейм данных
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
    'B':[103.02,107.26,110.35,114.23,114.68],
    'C':['big','small','big','small','small']})
Необходимо масштабировать его числовые столбцы.}$ 

In [25]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
dfTest=pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
'B':[103.02,107.26,110.35,114.23,114.68],
'C':['big','small','big','small','small']})

dfTest[['A','B']]=scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

$\small\textbf{3.3.2 Задание}$ $\small\textit{Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.}$ 

In [27]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)

X = df.drop('species', axis=1)
y = df['species']

scaler_minmax = MinMaxScaler()
X['sepal_length_cm'] = scaler_minmax.fit_transform(X[['sepal_length_cm']])

scaler_z = StandardScaler()
X['sepal_width_cm'] = scaler_z.fit_transform(X[['sepal_width_cm']])

print(X.head(2))


   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
0         0.222222        1.032057              1.4             0.2
1         0.166667       -0.124958              1.4             0.2
